### PR TITLE
Create container that retrieves NOAA URLs

### LINKED ISSUE #2: Requirement: Create a Docker Container that lists the URLs of NOAA GOES 16 Satellites
# 📖 Requirements
As a Meteorologist, I'd like to list the URLs for all the images from GOES-R of a specific date such as 31/01/2021, in order to download the images storaged in AWS S3. 

## Input 

`In this first implementation the user needs to do pass the following information:`
-  Satellite name: goes16 or goes17
-  ABI product such as ABI-L1b-RadC
-  Image retrieval year (YYYY format)
-  Image retrieval day (julian format: 001 - 366)
-  Image retrieval hour (HH format)

The option for the output is as follows:

- URL Format (http, s3)

**References to the GOES-R retrieval configuration:**
* [Beginners Guide](https://noaa-goes16.s3.amazonaws.com/Version1.1_Beginners_Guide_to_GOES-R_Series_Data.pdf)
* [NOAA GOES AWS - Guide](https://docs.opendata.aws/noaa-goes16/cics-readme.html)

## Output

* A list of URLs of the images to be downloaded `in the requested format`
  * `http`: URLs are in the format https://bucket.s3.amazom.com/path/to/image
  * `s3`: URLs are in the format s3://bucket.region.amazon.com/path/to/image

# 🎨 Design

* The requirements will be translated into a Shell script called `entrypoint.sh`. This script concatenates the information to form the bucket name and the path, then through `AWS CLI` executes `ls` recursively in the bucket aforementioned.  
 * The user can test it locally using bash/sh in terminal WITHOUT docker

* Explain how you can add the entrypoint to the Docker image
* Explain what the INPUT/OUTPUT for the "Container Blackbox" will be
  * Parameters used for Input based on the requirements 
  * Dependencies used inside the "Blackbox" such as AWS Client CLI
  * Explain the desired output like "List of URLs pointing to AWS S3"

# ✅ Acceptance Criteria

* When the user specifies `OUTPUT_FORMAT=http` 
  * the images are listed with `https://`
* When the user specifies `OUTPUT_FORMAT=s3` 
  * the images are listed with `s3://`
* All tests with filters
* All tests with date ranges

### PR DESCRIPTION
**Pull request by viniciusgcjr**
# 🆕 Features

* This PR solves the requirement at https://github.com/viniciusgcjr/data-science-machine-learning-engineering-docker/issues/2
* Creates a new Docker Image for a new Container that lists the URLs

## 🔧 Configuration

* `.env` file example

```
NOAA_SATELLITE_NAME=goes16
NOAA_ABI_PRODUCT_NAME=ABI-L1b-RadC
IMAGE_RETRIEVAL_YEAR=2021
IMAGE_RETRIEVAL_JULIAN_DAY=303
IMAGE_RETRIEVAL_HOUR=17
```

# 🔉 Logs

## Spikes
* Example running `entrypoint.sh` **without .env**
  * Providing all env vars using the command-line

```console
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# NOAA_SATELLITE_NAME=goes16 NOAA_ABI_PRODUCT_NAME=ABI-L1b-RadC IMAGE_RETRIEVAL_JULIAN_DAY=303 IMAGE_RETRIEVAL_HOUR=17 IMAGE_RETRIEVAL_YEAR=2020 bash entrypoint.sh 
* Retrieving images from satellite 'goes16' provided by 'noaa'
* Images location: 'noaa-goes16/ABI-L1b-RadC/2020/303/17'
=> Executing 'aws s3 --no-sign-request ls --recursive noaa-goes16/ABI-L1b-RadC/2020/303/17'
https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2020/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20203031701156_e20203031703529_c20203031703592.nc
https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2020/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20203031706156_e20203031708529_c20203031708584.nc
https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2020/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20203031711156_e20203031713529_c20203031713579.nc

```
cURL of the first URL retrieved by entrypoint.sh
```Logs
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# curl -I https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2020/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20203031701156_e20203031703529_c20203031703592.nc
HTTP/1.1 200 OK
x-amz-id-2: ta6t/NZNgk0DnRP4b6TH1/rF0BsWerg49XWDhbM1wq8o5UlKdEwVGBb37QbmSmMViLETb/OB8y8=
x-amz-request-id: 5TB4EECBSHA4D0VR
Date: Wed, 19 Jan 2022 19:34:29 GMT
Last-Modified: Thu, 29 Oct 2020 17:04:18 GMT
ETag: "c6d0bc39d84a1b000eb58305464ad2e7-2"
x-amz-storage-class: INTELLIGENT_TIERING
Accept-Ranges: bytes
Content-Type: binary/octet-stream
Server: AmazonS3
Content-Length: 14666050
```
* Example of running `entrypoint.sh` **with --env-file**
  * Same list of env vars

```console
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# set -o allexport; source goes16-lib-test.env; set +o allexport
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# bash entrypoint.sh 
* Retrieving images from satellite 'goes16' provided by 'noaa'
* Images location: 'noaa-goes16/ABI-L1b-RadC/2021/303/17'
=> Executing 'aws s3 --no-sign-request ls --recursive noaa-goes16/ABI-L1b-RadC/2021/303/17'
https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2021/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20213031701170_e20213031703543_c20213031703577.nc
https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2021/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20213031706170_e20213031708543_c20213031708597.nc
https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2021/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20213031711170_e20213031713543_c20213031713589.nc

```

##  Logs of the `docker build` command

```console
root@vinicius-ubuntu:/home/vinicius/data-science-machine-learning-engineering-docker/Run_with_entrypoint# docker build -t viniciusjr/noaa-satellite-images .
Sending build context to Docker daemon   7.68kB
Step 1/5 : FROM amazon/aws-cli:latest
 ---> 64bf4217f2c3
Step 2/5 : LABEl Author="Vinícius Gomes"
 ---> Using cache
 ---> d0961619b6b2
Step 3/5 : WORKDIR /data-science/image-processing/noaa
 ---> Using cache
 ---> d9f927c8af15
Step 4/5 : COPY entrypoint.sh .
 ---> 4a17af5f7a01
Step 5/5 : ENTRYPOINT [ "sh", "/data-science/image-processing/noaa/entrypoint.sh" ]
 ---> Running in 378f4ae6756e
Removing intermediate container 378f4ae6756e
 ---> 79652af36e37
Successfully built 79652af36e37
Successfully tagged viniciusjr/noaa-satellite-images:latest
```

## Provide the logs of the `docker run` commands

* Providing all env vars using the command-line
```console
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# docker run -it --env NOAA_SATELLITE_NAME="goes16" --env NOAA_ABI_PRODUCT_NAME="ABI-L1b-RadC" --env IMAGE_RETRIEVAL_JULIAN_DAY="015" --env IMAGE_RETRIEVAL_HOUR="17" --env IMAGE_RETRIEVAL_YEAR=2022 viniciusjr/noaa-satellite-images
* Retrieving images from satellite 'goes16' provided by 'noaa'
* Images location: 'noaa-goes16/ABI-L1b-RadC/2022/015/17'
=> Executing 'aws s3 --no-sign-request ls --recursive noaa-goes16/ABI-L1b-RadC/2022/015/17'
https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2022/015/17/OR_ABI-L1b-RadC-M6C01_G16_s20220151701173_e20220151703546_c20220151703579.nc
https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2022/015/17/OR_ABI-L1b-RadC-M6C01_G16_s20220151706173_e20220151708546_c20220151708585.nc
https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2022/015/17/OR_ABI-L1b-RadC-M6C01_G16_s20220151711173_e20220151713546_c20220151713585.nc
```

* Providing all env vars using ```.env```
```console
root@vinicius-ubuntu:/home/vinicius/data-science-machine-learning-engineering-docker/Run_with_entrypoint# docker run -it --env-file=goes16-lib-test.env viniciusjr/noaa-satellite-images
* Retrieving images from satellite 'goes16' provided by 'noaa'
* Images location: 'noaa-goes16/ABI-L1b-RadC/2021/303/17'
=> Executing 'aws s3 --no-sign-request ls --recursive noaa-goes16/ABI-L1b-RadC/2021/303/17'
https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2021/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20213031701170_e20213031703543_c20213031703577.nc
https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2021/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20213031706170_e20213031708543_c20213031708597.nc
https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2021/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20213031711170_e20213031713543_c20213031713589.nc
```

##  Provide the logs of the `docker compose build` command

```console
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# docker-compose buildBuilding noaa-satellite-images
Step 1/5 : FROM amazon/aws-cli:latest
 ---> 64bf4217f2c3
Step 2/5 : LABEl Author="Vinícius Gomes"
 ---> Using cache
 ---> d0961619b6b2
Step 3/5 : WORKDIR /data-science/image-processing/noaa
 ---> Using cache
 ---> d9f927c8af15
Step 4/5 : COPY entrypoint.sh .
 ---> fbf326b15a4e
Step 5/5 : ENTRYPOINT [ "sh", "/data-science/image-processing/noaa/entrypoint.sh" ]
 ---> Running in 2b87e50791e3
Removing intermediate container 2b87e50791e3
 ---> 2606dcfb52a5

Successfully built 2606dcfb52a5
Successfully tagged viniciusjr/noaa-satellite-images:latest
```

## Provide the logs of the `docker compose up` commands
```
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# docker compose  up
[+] Running 1/1
 ⠿ Container run_with_entrypoint-noaa-satellite-images-1  Recreat...                                                         1.8s
Attaching to run_with_entrypoint-noaa-satellite-images-1
run_with_entrypoint-noaa-satellite-images-1  | * Retrieving images from satellite 'goes16' provided by 'noaa'
run_with_entrypoint-noaa-satellite-images-1  | * Images location: 'noaa-goes16/ABI-L1b-RadC/2021/303/17'
run_with_entrypoint-noaa-satellite-images-1  | => Executing 'aws s3 --no-sign-request ls --recursive noaa-goes16/ABI-L1b-RadC/2021/303/17'
run_with_entrypoint-noaa-satellite-images-1  | https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2021/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20213031701170_e20213031703543_c20213031703577.nc
run_with_entrypoint-noaa-satellite-images-1  | https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2021/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20213031706170_e20213031708543_c20213031708597.nc
run_with_entrypoint-noaa-satellite-images-1  | https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2021/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20213031711170_e20213031713543_c20213031713589.nc
...
run_with_entrypoint-noaa-satellite-images-1  | https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2021/303/17/OR_ABI-L1b-RadC-M6C16_G16_s20213031746170_e20213031748555_c20213031748595.nc
run_with_entrypoint-noaa-satellite-images-1  | https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2021/303/17/OR_ABI-L1b-RadC-M6C16_G16_s20213031751170_e20213031753554_c20213031754004.nc
run_with_entrypoint-noaa-satellite-images-1  | https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2021/303/17/OR_ABI-L1b-RadC-M6C16_G16_s20213031756170_e20213031758554_c20213031759011.nc
run_with_entrypoint-noaa-satellite-images-1 exited with code 0
```

## Logs ```Docker compose up --build``` with ```.env``` and ```--env-file```:

- ```with --env-file```:
```
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# docker compose  --env-file=goes16-lib-test.env up --build
Sending build context to Docker daemon  1.391kB
Step 1/5 : FROM amazon/aws-cli:latest
 ---> 64bf4217f2c3
Step 2/5 : LABEl Author="Vinícius Gomes"
 ---> Using cache
 ---> d0961619b6b2
Step 3/5 : WORKDIR /data-science/image-processing/noaa
 ---> Using cache
 ---> d9f927c8af15
Step 4/5 : COPY entrypoint.sh .
 ---> 794d7ebdbbfe
Step 5/5 : ENTRYPOINT [ "sh", "/data-science/image-processing/noaa/entrypoint.sh" ]
 ---> Running in 4cc81e082aaa
Removing intermediate container 4cc81e082aaa
 ---> 16f40b3fe8c6
Successfully built 16f40b3fe8c6
Successfully tagged viniciusjr/noaa-satellite-images-api:latest

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 1/1
 ⠿ Container run_with_entrypoint-noaa-satellite-images-1  Recreat...                                                         1.7s
Attaching to run_with_entrypoint-noaa-satellite-images-1
run_with_entrypoint-noaa-satellite-images-1  | * Retrieving images from satellite 'goes16' provided by 'noaa'
run_with_entrypoint-noaa-satellite-images-1  | * Images location: 'noaa-goes16/ABI-L1b-RadC/2020/303/17'
run_with_entrypoint-noaa-satellite-images-1  | => Executing 'aws s3 --no-sign-request ls --recursive noaa-goes16/ABI-L1b-RadC/2020/303/17'
run_with_entrypoint-noaa-satellite-images-1  | https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2020/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20203031701156_e20203031703529_c20203031703592.nc
run_with_entrypoint-noaa-satellite-images-1  | https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2020/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20203031706156_e20203031708529_c20203031708584.nc
run_with_entrypoint-noaa-satellite-images-1  | https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2020/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20203031711156_e20203031713529_c20203031713579.nc
run_with_entrypoint-noaa-satellite-images-1  | https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadC/2020/303/17/OR_ABI-L1b-RadC-M6C01_G16_s20203031716156_e20203031718529_c20203031718585.nc

```
-with ```.env```:

```
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# docker compose  up --build
Sending build context to Docker daemon  1.391kB
Step 1/5 : FROM amazon/aws-cli:latest
 ---> 64bf4217f2c3
Step 2/5 : LABEl Author="Vinícius Gomes"
 ---> Using cache
 ---> d0961619b6b2
Step 3/5 : WORKDIR /data-science/image-processing/noaa
 ---> Using cache
 ---> d9f927c8af15
Step 4/5 : COPY entrypoint.sh .
 ---> Using cache
 ---> 794d7ebdbbfe
Step 5/5 : ENTRYPOINT [ "sh", "/data-science/image-processing/noaa/entrypoint.sh" ]
 ---> Using cache
 ---> 16f40b3fe8c6
Successfully built 16f40b3fe8c6
Successfully tagged viniciusjr/noaa-satellite-images-api:latest

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 1/1
 ⠿ Container run_with_entrypoint-noaa-satellite-images-1  Recreat...                                                         1.8s
Attaching to run_with_entrypoint-noaa-satellite-images-1
run_with_entrypoint-noaa-satellite-images-1  | * Retrieving images from satellite 'goes17' provided by 'noaa'
run_with_entrypoint-noaa-satellite-images-1  | * Images location: 'noaa-goes17/ABI-L1b-RadC/2021/222/22'
run_with_entrypoint-noaa-satellite-images-1  | => Executing 'aws s3 --no-sign-request ls --recursive noaa-goes17/ABI-L1b-RadC/2021/222/22'
run_with_entrypoint-noaa-satellite-images-1  | https://noaa-goes17.s3.amazonaws.com/ABI-L1b-RadC/2021/222/22/OR_ABI-L1b-RadC-M6C01_G17_s20212222201177_e20212222203550_c20212222203577.nc
run_with_entrypoint-noaa-satellite-images-1  | https://noaa-goes17.s3.amazonaws.com/ABI-L1b-RadC/2021/222/22/OR_ABI-L1b-RadC-M6C01_G17_s20212222206177_e20212222208550_c20212222208579.nc
run_with_entrypoint-noaa-satellite-images-1  | https://noaa-goes17.s3.amazonaws.com/ABI-L1b-RadC/2021/222/22/OR_ABI-L1b-RadC-M6C01_G17_s20212222211177_e20212222213550_c20212222213579.nc
```

# :heavy_check_mark: Test cases

## Validating Input

* Input parameters are validated in order
``` 
NOAA_SATELLITE_NAME
NOAA_ABI_PRODUCT_NAME 
IMAGE_RETRIEVAL_JULIAN_DAY
IMAGE_RETRIEVAL_HOUR
IMAGE_RETRIEVAL_YEAR
```

```
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# NOAA_ABI_PRODUCT_NAME=ABI-L1b-RadC IMAGE_RETRIEVAL_JULIAN_DAY=015 IMAGE_RETRIEVAL_HOUR=06 IMAGE_RETRIEVAL_YEAR=1999 bash entrypoint.sh 
entrypoint.sh: line 3: NOAA_SATELLITE_NAME: You need provide the satellite name such as goes16
```
```
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# NOAA_SATELLITE_NAME=goes17 IMAGE_RETRIEVAL_JULIAN_DAY=015 IMAGE_RETRIEVAL_HOUR=06 IMAGE_RETRIEVAL_YEAR=1999 bash entrypoint.sh 
entrypoint.sh: line 4: NOAA_ABI_PRODUCT_NAME: You need provide the ABI product name such as ABI-L1b-RadC
```
```
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# NOAA_SATELLITE_NAME=goes17 NOAA_ABI_PRODUCT_NAME=ABI-L1b-RadC IMAGE_RETRIEVAL_HOUR=06 IMAGE_RETRIEVAL_YEAR=1999 bash entrypoint.sh 
entrypoint.sh: line 6: IMAGE_RETRIEVAL_JULIAN_DAY: You need provide the image retrieval day (julian format: 1-366
```
```
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# NOAA_SATELLITE_NAME=goes17 NOAA_ABI_PRODUCT_NAME=ABI-L1b-RadC IMAGE_RETRIEVAL_JULIAN_DAY=015 IMAGE_RETRIEVAL_YEAR=1999 bash entrypoint.sh 
entrypoint.sh: line 7: IMAGE_RETRIEVAL_HOUR: You need provide the image retrieval hour (HH format)
```
```
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# NOAA_SATELLITE_NAME=goes17 NOAA_ABI_PRODUCT_NAME=ABI-L1b-RadC IMAGE_RETRIEVAL_JULIAN_DAY=015 IMAGE_RETRIEVAL_HOUR=06 bash entrypoint.sh 
entrypoint.sh: line 5: IMAGE_RETRIEVAL_YEAR: You need provide the image retrieval year (YYYY format)
```
## .env test cases

* Example running without .env
  * `2022 - Hunga Tonga eruption and tsunami` 
```
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# NOAA_SATELLITE_NAME=goes17 NOAA_ABI_PRODUCT_NAME=ABI-L1b-RadC IMAGE_RETRIEVAL_JULIAN_DAY=015 IMAGE_RETRIEVAL_HOUR=06 IMAGE_RETRIEVAL_YEAR=2022 bash entrypoint.sh 
* Retrieving images from satellite 'goes17' provided by 'noaa'
* Images location: 'noaa-goes17/ABI-L1b-RadC/2022/015/06'
=> Executing 'aws s3 --no-sign-request ls --recursive noaa-goes17/ABI-L1b-RadC/2022/015/06'
https://noaa-goes17.s3.amazonaws.com/ABI-L1b-RadC/2022/015/06/OR_ABI-L1b-RadC-M6C01_G17_s20220150601178_e20220150603551_c20220150603586.nc
https://noaa-goes17.s3.amazonaws.com/ABI-L1b-RadC/2022/015/06/OR_ABI-L1b-RadC-M6C01_G17_s20220150606178_e20220150608551_c20220150608580.nc
https://noaa-goes17.s3.amazonaws.com/ABI-L1b-RadC/2022/015/06/OR_ABI-L1b-RadC-M6C01_G17_s20220150611178_e20220150613551_c20220150613583.nc

```
  * `Example with invalid date (before GOES-R launch): year 1999`
  
```
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# NOAA_SATELLITE_NAME=goes17 NOAA_ABI_PRODUCT_NAME=ABI-L1b-RadC IMAGE_RETRIEVAL_JULIAN_DAY=015 IMAGE_RETRIEVAL_HOUR=06 IMAGE_RETRIEVAL_YEAR=1999 bash entrypoint.sh 
* Retrieving images from satellite 'goes17' provided by 'noaa'
* Images location: 'noaa-goes17/ABI-L1b-RadC/1999/015/06'
=> Executing 'aws s3 --no-sign-request ls --recursive noaa-goes17/ABI-L1b-RadC/1999/015/06'
root@vinicius-ubuntu:/home/vinicius/Documents/dev/data-science-machine-learning-engineering-docker/Run_with_entrypoint# 
```

# 📝 Documentation

* Create/Update the README with basic information on:
  * How to build a docker image
  * How to run a container manually from the image

### CODE REVIEW

**Comment by marcellodesales** [comment]
# Review 1

* It's a great start @viniciusgcjr!!! Let's move a bit forward
* Please fill out the PR's section by editing the PR content
* Provide information on them as much as you can
* Please review the requested changes that are `Pending`

**Comment by marcellodesales** [comment]
# Review 2

* Just add the `docker-compose` build information
  * `docker-compose.yaml` is still missing the `build` properties
* Make sure to verify the output of the docker-compose
* Also, the exit status when there's a failure

**Comment by KaramJameelMoore** [comment]
Karam Jameel Moore

**Comment by viniciusgcjr** [comment]
S3 and HTTPS options will be available in the next PR.

**Pull request merged**
